<template>
  <div class="body_container">
    <div class="m-2">
      <h4>Body</h4>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
      <span>Lorem ipsum dolor sit amet odio nobis laborum.</span>
    </div>
  </div>
</template>
<script>
export default {
  name: "BodyComponent",
};
</script>
